# Generated by Django 5.1.5 on 2025-01-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='secondary_logo',
            field=models.ImageField(blank=True, null=True, upload_to='sitesettings/'),
        ),
    ]
