# Generated by Django 5.1.5 on 2025-01-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partner/')),
            ],
        ),
    ]
