# Generated by Django 5.1.5 on 2025-01-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('insurance', models.CharField(choices=[('Life Insurance', 'Life Insurance'), ('Car Insurance', 'Car Insurance'), ('Health Insurance', 'Health Insurance'), ('Home & Industrial Insurance', 'Home & Industrial Insurance'), ('Fire Insurance', 'Fire Insurance'), ('Transit Insurance', 'Transit Insurance')], default='Car Insurance', max_length=200)),
            ],
        ),
    ]
