# Generated by Django 5.1.5 on 2025-01-24 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero/multiple/')),
                ('hero_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='index.herosection')),
            ],
        ),
    ]
