# Generated by Django 5.1.5 on 2025-02-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_heroimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='client/')),
            ],
        ),
    ]
