# Generated by Django 5.1.5 on 2025-02-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_clientlogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowToClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hoe_to_claim/')),
            ],
        ),
    ]
