# Generated by Django 5.1.5 on 2025-02-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_howtoclaim'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='admin2_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='admin2_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='admin2_position',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
